# Generated by Django 5.2.6 on 2025-11-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="prefer_elevator",
            new_name="require_elevator",
        ),
    ]
