# Generated by Django 5.2.6 on 2025-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_prefer_elevator_userprofile_require_elevator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="prefer_ramps",
            new_name="aovid_ramps",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="require_elevator",
            new_name="aovid_stairs",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="priority_accessibility",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="movemnet_condition",
            field=models.CharField(
                choices=[
                    ("none", "해당 없음"),
                    ("wheelchair", "휠체어 이용"),
                    ("visual_impaired", "시각 장애"),
                    ("leg_fracture", "다리 골절"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="prefer_elevator",
            field=models.BooleanField(default=False),
        ),
    ]
