# Generated by Django 5.2.6 on 2025-11-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_prefer_ramps_userprofile_aovid_ramps_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="movemnet_condition",
            new_name="movement_condition",
        ),
    ]
