# Generated by Django 5.2.6 on 2025-11-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_movemnet_condition_userprofile_movement_condition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="aovid_stairs",
            new_name="avoid_stairs",
        ),
    ]
