# Generated by Django 5.2.6 on 2025-11-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_aovid_stairs_userprofile_avoid_stairs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="aovid_ramps",
            new_name="avoid_ramps",
        ),
    ]
