# Generated by Django 5.2.6 on 2025-11-21 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_aovid_ramps_userprofile_avoid_ramps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avoid_ramps",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avoid_stairs",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="movement_condition",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="prefer_elevator",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
