# Generated by Django 5.2.8 on 2025-11-20 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('ELEVATOR', '엘리베이터'), ('RAMP', '경사로'), ('TOILET', '장애인 화장실'), ('SHELTER', '쉼터'), ('BLIND_WALK', '시각장애인 유도블록')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_operational', models.BooleanField(default=True)),
                ('external_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheelchair_user', models.BooleanField(default=False)),
                ('blind_user', models.BooleanField(default=False)),
                ('leg_injury_user', models.BooleanField(default=False)),
                ('senior_user', models.BooleanField(default=False)),
                ('no_stair', models.BooleanField(default=False)),
                ('no_slopes', models.BooleanField(default=False)),
                ('yes_elevator', models.BooleanField(default=False)),
                ('yes_escalator', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
