# Generated by Django 5.2.6 on 2025-11-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="blind_user",
        ),
    ]
